# Based on:
# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku
# 
# Modified by ArthorYCoed for Lily58 keyboard and custom config

name: 'Build Lily58 nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left nice_view_adapter nice_view","lily58_right nice_view_adapter nice_view"]'
      clipboard: '["win"]'
